name: Build & publish JSON daily

on:
  schedule:
    # Expressed in UTC. 04:10 UTC ≈ 06:10 CEST / 05:10 CET
    # Runs Monday to Friday only (1-5 in cron day-of-week)
    - cron: '10 4 * * 1-5'
  workflow_dispatch: {}

permissions:
  contents: write  # to commit in the repo

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare docs folder
        run: mkdir -p docs
        
      - name: Run script
        run: |
          python update_data_script.py

      - name: Commit & push (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/output_enriched.json
          git commit -m "chore: update JSON ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))" || echo "No changes to commit"
          git push
